// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repositories.DbConfiguration;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125122136_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LaundryProgramMachine", b =>
                {
                    b.Property<Guid>("MachinesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgramsId")
                        .HasColumnType("uuid");

                    b.HasKey("MachinesId", "ProgramsId");

                    b.HasIndex("ProgramsId");

                    b.ToTable("LaundryProgramMachine");
                });

            modelBuilder.Entity("Repositories.Laundry.Entity.Laundry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hours")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("PersonEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonEntityId");

                    b.ToTable("Laundries");
                });

            modelBuilder.Entity("Repositories.Laundry.Entity.LaundryProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<int>("Temperature")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("Repositories.Laundry.Entity.LaundryStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrentProgramId");

                    b.HasIndex("MachineId")
                        .IsUnique();

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("Repositories.Laundry.Entity.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LaundryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("PersonEntityId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LaundryId");

                    b.HasIndex("PersonEntityId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Repositories.User.PersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("PersonType")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Repositories.User.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LaundryProgramMachine", b =>
                {
                    b.HasOne("Repositories.Laundry.Entity.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Laundry.Entity.LaundryProgram", null)
                        .WithMany()
                        .HasForeignKey("ProgramsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repositories.Laundry.Entity.Laundry", b =>
                {
                    b.HasOne("Repositories.User.PersonEntity", null)
                        .WithMany("Laundries")
                        .HasForeignKey("PersonEntityId");
                });

            modelBuilder.Entity("Repositories.Laundry.Entity.LaundryStatus", b =>
                {
                    b.HasOne("Repositories.Laundry.Entity.LaundryProgram", "CurrentProgram")
                        .WithMany()
                        .HasForeignKey("CurrentProgramId");

                    b.HasOne("Repositories.Laundry.Entity.Machine", "Machine")
                        .WithOne("LaundryStatus")
                        .HasForeignKey("Repositories.Laundry.Entity.LaundryStatus", "MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentProgram");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("Repositories.Laundry.Entity.Machine", b =>
                {
                    b.HasOne("Repositories.Laundry.Entity.Laundry", "Laundry")
                        .WithMany("Machines")
                        .HasForeignKey("LaundryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.User.PersonEntity", null)
                        .WithMany("Machines")
                        .HasForeignKey("PersonEntityId");

                    b.Navigation("Laundry");
                });

            modelBuilder.Entity("Repositories.User.UserEntity", b =>
                {
                    b.HasOne("Repositories.User.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Repositories.Laundry.Entity.Laundry", b =>
                {
                    b.Navigation("Machines");
                });

            modelBuilder.Entity("Repositories.Laundry.Entity.Machine", b =>
                {
                    b.Navigation("LaundryStatus")
                        .IsRequired();
                });

            modelBuilder.Entity("Repositories.User.PersonEntity", b =>
                {
                    b.Navigation("Laundries");

                    b.Navigation("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
